SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/dac_channel_regs.v
TOPLEVEL = dac_channel_regs
MODULE = test_dac_channel_regs

include $(shell cocotb-config --makefiles)/Makefile.sim
